Remove unnecessary use of vec macro
Clippy emits:

 error: useless use of `vec!`

As suggested, remove the macro call. Rename the variable to `bytes`
instead of `v` to better suit the new array type.